# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"

# binary install as per travis instructions
# used to install latest version of ghdl
before_script:
  - ./scripts/install_ghdl.sh
  - export PATH=$PATH:$PWD/ghdl-0.33/bin/

addons:
  apt:
    # sources:
    #  - pgavin-ghdl
    packages:
      - iverilog
    #  - ghdl

install:
  - pip install .

env:
  - CI_TARGET=core
  - CI_TARGET=iverilog
  - CI_TARGET=ghdl

script: ./scripts/ci.sh

notifications:
  email: false
