# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.4"

addons:
  apt_sources:
    - pgavin-ghdl
  apt_packages:
    - iverilog
    - ghdl

install:
  - pip install .

env:
  - CI_TARGET=core
  - CI_TARGET=icarus
  - CI_TARGET=ghdl
  - CI_TARGET=bugs

matrix:
  allow_failures:
    - python: "3.4"

script: ./ci.sh

notifications:
  email: false
