# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"

addons:
  apt:
    sources:
      - pgavin-ghdl
    packages:
      - iverilog
      - ghdl

install:
  - pip install .

env:
  - CI_TARGET=core
  - CI_TARGET=iverilog
  - CI_TARGET=ghdl

matrix:
  allow_failures:
    - python: "3.4"
      env: CI_TARGET=iverilog
    - python: "3.4"
      env: CI_TARGET=ghdl
    - python: "3.5"
      env: CI_TARGET=iverilog
    - python: "3.5"
      env: CI_TARGET=ghdl

script: ./scripts/ci.sh

notifications:
  email: false
